### ISSUE TITLE
Hang on starting cgroups cleanup

### ISSUE THREAD

**Issue by mlen** [OpenRC/openrc#166]
I have cgroup cleanup feature enabled and openrc hangs during cleanup for considerable amount of time for every service. This happens with version 0.31.2. Not sure how can I provide additional information or help to debug this. Booting works perfectly fine, though.

**Comment by mlen** [comment]
Previous known working version was 0.29

**Comment by cromerc** [comment]
In the newever versions of openrc both cgroups v1 and v2 are now implemented. Does your cgroups cleanup feature use cgroups v1 or v2? Make sure to configure cgroups in the openrc rc.conf file. By default it has hybrid turned on which is a mixture of v1 and v2. If you just want legacy like it was before v2 was added, change cgroups to legacy in rc.conf.

**Comment by williamh** [comment]
In the newer versions of OpenRC, you can also use the rc_timeout_stopsec variable to shorten the amount of time the cgroup_cleanup delays.

**Comment by mlen** [comment]
@williamh thanks. What is the purpose of sending cont signal after sending term? The amount of time it'll sleep is determined by the mentioned variable, but it seems that openrc will always sleep this long. Maybe some polling solution would be better to detect cases when processes have exited earlier?

**Comment by CryCic4da** [comment]
experiecing the same problem on a gentoo install.

**Comment by williamh** [comment]
This should be fixed in 0.34.10.

**Comment by saboya** [comment]
Tested it today in a Gentoo install, still an issue with xdm.

**Comment by saboya** [comment]
I believe the xdm issue is caused by this commit:

https://github.com/OpenRC/openrc/commit/6a5ca2ab368d0a85f51bb559672dba2e3ffcc6be

Don't know if it's poor signal handling by one of the child processes.

**Comment by williamh** [comment]
@saboya Is it happening with any services other than xdm?

**Comment by saboya** [comment]
I'm not sure, it may be that xdm is hanging first and, since it never shuts down, OpenRC just kills everything after the timeout.

I have a particular setup with Gnome 3.26 without systemd (dantrell overlay), which uses `elogind`. Another user with the same setup, but a different version (3.22) doesn't seem to have any problems.

3.26 uses `elogind` while 3.22 still uses `consolekit`, so the issue has something to do with `elogind`, which is probably a child process of `gdm`, which itself is a child process of `xdm`.

Using `rc_send_sighup="YES"` solves the issue.

**Comment by williamh** [comment]
In that case, I'll go ahead and close this issue.
