### ISSUE TITLE
several cgroup.proc no such file or directory open-rc-0.34.11 gentoo-sources-4.14.13

### ISSUE THREAD

**Issue by djdunn** [OpenRC/openrc#200]
attached the rc.log
~amd64
open-rc-0.34.11
gentoo-sources-4.14.13

rc.log (sorry couldn't get the code tags to work)
`rc sysinit logging started at Wed Jan 17 04:56:34 2018

   OpenRC 0.34.11 is starting up Gentoo Linux (x86_64)

 * /proc is already mounted
 * Mounting /run ...
 * /run/openrc: creating directory
 * /run/lock: creating directory
 * /run/lock: correcting owner
 * Caching service dependencies ...
 [ ok ]  
mkdir: cannot create directory ‘/sys/fs/cgroup/devfs’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/devfs/cgroup.procs: No such 
file or directory
 * Remounting devtmpfs on /dev ...
 [ ok ]  
 * Mounting /dev/mqueue ...
 [ ok ]  
 * Mounting /dev/shm ...
 [ ok ]  
mkdir: cannot create directory ‘/sys/fs/cgroup/dmesg’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/dmesg/cgroup.procs: No such 
file or directory
mkdir: cannot create directory ‘/sys/fs/cgroup/kmod-static-nodes’: No such file 
or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/kmod-static-nodes/cgroup.pro
cs: No such file or directory
 * Creating list of required static device nodes for the current kernel ...
[ ok ]  
mkdir: cannot create directory ‘/sys/fs/cgroup/opentmpfiles-dev’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/opentmpfiles-dev/cgroup.procs: No such file or directory
 * Setting up tmpfiles.d entries for /dev ...
 [ ok ]  
 [ ok ]  
mkdir: cannot create directory ‘/sys/fs/cgroup/sysfs’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/sysfs/cgroup.procs: No such 
file or directory
 * Mounting debug filesystem ...
 [ ok ]  
 * Mounting config filesystem ...
 [ ok ]`

**Comment by udeved** [comment]
I can confirm this with artix kernel 4.14, openrc unified cgroups set, and elogind compiled with hybrid cg.

**Comment by djdunn** [comment]
Only happens for me with 
rc_cgroup_mode="unified"

**Comment by udeved** [comment]
Confirm, if it is set explicitly to unified.

**Comment by williamh** [comment]
This should be resolved in 0.35.5.
If it isn't, let me know and I'll re-open the issue.

Thanks,

William

**Comment by Hawk777** [comment]
With `rc_cgroup_mode=unified`, I still get this with sys-apps/openrc-0.38.3-r1. The directories that fail are `/sys/fs/cgroup/sysfs` and `/sys/fs/cgroup/cgroups`, so not exactly the same directories—not sure if you count that as part of this bug or if you prefer a new ticket?

**Comment by E5ten** [comment]
I get the same issue as Hawk777.

**Comment by Hawk777** [comment]
No reply, so I filed GH-307.
